#pragma once

#define ENI_MAKE_NRFX_TIMER_DESCRIPTION(n) nrfx_timer_t{NRFX_CONCAT_2(NRF_TIMER, n), NRFX_CONCAT_3(NRFX_TIMER, n, _INST_IDX), NRF_TIMER_CC_CHANNEL_COUNT(n)}

#define ENI_MAKE_NRFX_SPIS_DESCRIPTION(n)  nrfx_spis_t{NRFX_CONCAT_2(NRF_SPIS, n), NRFX_CONCAT_3(NRFX_SPIS, n, _INST_IDX)}

#define ENI_MAKE_NRFX_PWM_DESCRIPTION(n) nrfx_pwm_t{NRFX_CONCAT_2(NRF_PWM, n), NRFX_CONCAT_3(NRFX_PWM, n, _INST_IDX)}

#define ENI_MAKE_NRFX_TWIM_DESCRIPTION(n) nrfx_twim_t{NRFX_CONCAT_2(NRF_TWIM, n), NRFX_CONCAT_3(NRFX_TWIM, n, _INST_IDX)}
